name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main # 或者你的默认分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8.8.0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install Dependencies
        run: |
          cd uni-app-version
          pnpm install

      - name: Build
        run: |
          cd uni-app-version
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # GitHub Pages 分支
          folder: uni-app-version/dist # 构建的文件夹
